Build: assignmentAdd.c rtGetNaN.c assignmentAdd.h assignmentAdd_terminate.c main.c rtGetNaN.h assignmentAdd_initialize.c assignmentAdd_terminate.h main.h rt_nonfinite.c  assignmentAdd_initialize.h  assignmentAdd_types.h rt_nonfinite.h  rtGetInf.c rtGetInf.h rtwtypes.h
	gcc  assignmentAdd.c rtGetNaN.c assignmentAdd.h assignmentAdd_terminate.c main.c rtGetNaN.h assignmentAdd_initialize.c assignmentAdd_terminate.h main.h rt_nonfinite.c  assignmentAdd_initialize.h  assignmentAdd_types.h rt_nonfinite.h  rtGetInf.c rtGetInf.h rtwtypes.h -o out.exe
	
	


